remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
navigation:
  - text: Home
    url: /
  - text: Slides
    url: /slides/
  - text: Resources
    url: /resources/
  - text: Assignments
    url: /assignments/