remote_theme: pmarsceill/just-the-docs
theme: ./_includes/just-the-docs
navigation:
  - text: Home
    url: /
  - text: Slides
    url: /slides/
  - text: Resources
    url: /resources/
  - text: Assignments
    url: /assignments/